pull_request_rules:
  - name: automatic merge Scala Steward PRs on CI success
    conditions:
      - status-success=ci/circleci: build
      - author=@scala-steward
    actions:
      merge:
        method: merge
