name: Console4Cats
baseurl: /console4cats
description: Console I/O for Cats Effect
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.6.0
org: Console for Cats
markdown: kramdown
